version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      timezone: "Europe/Berlin"
      interval: "weekly"
      day: "wednesday"
      time: "07:00"
    assignees:
      - nikcani
    groups:
      bun:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      timezone: "Europe/Berlin"
      interval: "weekly"
      day: "wednesday"
      time: "07:00"
    assignees:
      - nikcani
    groups:
      github-actions:
        patterns:
          - "*"
