name: publish-to-npmjs

on:
  push:
    tags:
      - "*.*.*"

jobs:
  trufflehog:
    uses: ./.github/workflows/trufflehog.yml
  build-and-publish:
    needs:
      - trufflehog
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - run: bun run prod
      - run: bun publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
